name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main
      - "feat/**"
      - "fix/**"
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

  semgrep-sast:
    name: SAST - Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        run: |
          docker run --rm -v "$PWD:/src" semgrep/semgrep semgrep scan --config auto /src --exclude node_modules --exclude .git --exclude evidence

  dependency-scan:
    name: Dependency Scan - npm audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --audit-level=high

  secrets-scan:
    name: Secrets Scan - Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        run: |
          docker run --rm -v "$PWD:/path" zricethezav/gitleaks:latest detect --source="/path" --verbose

  container-scan:
    name: Container Scan - Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nodegoat-devsecops:ci .

      - name: Run Trivy image scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL nodegoat-devsecops:ci
